#!/bin/sh
#
# spacenavd      free driver for 3Dconnexion 6dof devices
#
# chkconfig: 2345 99 99
# description: A free user space driver for 3Dconnexion input devices,\
#              compatible with the proprietary 3dxsrv daemon.

DAEMON=/usr/local/bin/spacenavd

[ -x "$DAEMON" ] || exit 0

case "$1" in
start)
	echo 'Starting spacenavd daemon'
	$DAEMON -v
	;;

stop)
	echo 'Stopping spacenavd daemon'
	kill `pidof spacenavd`
	;;

reload|restart|force-reload)
	$0 stop && $0 start
	;;
esac
